version: '3.9'

services:
  grafana:
    build: 
      context: .
      args:
        grafana_version: ${GRAFANA_VERSION}
    volumes:
      - ./dist:/var/lib/grafana/plugins/basic-panel
      - ./provisioning:/etc/grafana/provisioning

  cypress:
    image: cypress/included:8.4.1
    entrypoint: 'yarn grafana-e2e'
    working_dir: /e2e
    volumes:
      - .:/e2e
    environment:
      - CYPRESS_BASE_URL=http://grafana:3000
    depends_on:
      - grafana
