version: '3.0'

services:
  grafana:
    container_name: 'basic-datasource'
    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-dev}
        grafana_version: ${GRAFANA_VERSION:-10.2.0-137158}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/basic-datasource
      - ./provisioning:/etc/grafana/provisioning
