version: '3.0'

services:
  grafana:
    build: .
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/basic-datasource
      - ./provisioning:/etc/grafana/provisioning