version: '3.0'

services:
  grafana:
    container_name: 'panel-frame-select'
    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-10.3.3}
    environment:
      - GF_INSTALL_PLUGINS=marcusolsson-static-datasource
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/example
      - ./provisioning:/etc/grafana/provisioning
