version: '3.0'

services:
  grafana:
    container_name: 'example-websocket-datasource'
    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-9.5.3}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/example-websocket-datasource
      - ./provisioning:/etc/grafana/provisioning
  websocket-server:
    container_name: 'websocket-server-example'
    build:
      context: ../websocket-server
    ports:
      - 8080:8080/tcp
