version: '3.0'

services:
  grafana:
    container_name: 'example-websocket-backend-datasource'
    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-10.3.3}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/example-websocket-datasource
      - ./provisioning:/etc/grafana/provisioning
    extra_hosts:
      - 'host.docker.internal:host-gateway'
  mockserver:
    container_name: 'mockserver-streamingbackend-datasource'
    build:
      context: ../websocket-server
    ports:
      - 8080:8080/tcp
