version: '3.0'

services:
  grafana:
    container_name: 'grafana-appwithrbac-app'
    platform: 'linux/amd64'
    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-dev}
        grafana_version: ${GRAFANA_VERSION:-11.2.0-185307}
    environment:
      - GF_FEATURE_TOGGLES_ENABLE=accessControlOnCall,idForwarding,externalServiceAccounts
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/grafana-appwithrbac-app
      - ./provisioning:/etc/grafana/provisioning
