name: Merge Changes
description: Open PR with changes and merge it if all tests are passed
inputs:
  app-id:
    description: GitHub App ID
    required: true
  app-pem:
    description: GitHub App PEM
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up Git configuration
      shell: bash
      run: |
        git config user.name 'grafana-delivery-bot[bot]'
        git config user.email '132647405+grafana-delivery-bot[bot]@users.noreply.github.com'

    - name: Generate token
      id: generate_token
      uses: tibdex/github-app-token@v2
      with:
        app_id: "${{ inputs.app-id }}"
        private_key: "${{ inputs.app-pem }}"

    - name: Create PR
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ steps.generate_token.outputs.token }}
        branch: new-update-plugin-examples
        delete-branch: true
        commit-message: 'chore: update configuration to latest version'
        title: 'Chore: Bump plugin-examples configuration to latest version'
        body: |
          Bumps [`grafana-plugin-examples`](https://github.com/grafana/grafana-plugin-examples) configuration to the latest version.

          **Notes for reviewer:**
          This is an auto-generated PR which ran `npx -y @grafana/create-plugin@latest update`, updates plugin.json files and docker-compose files for each plugin example
          Please review the changes thoroughly before merging.
