version: '3.0'

services:
  grafana:
    container_name: 'myorg-extensionpoint-app'
    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-11.5.1}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/myorg-extensionpoint-app
      - ./provisioning:/etc/grafana/provisioning
