version: '3.0'

services:
  grafana:
    container_name: 'myorg-extensions-app'
    build:
      context: ./.config
      args:
        grafana_version: ${GRAFANA_VERSION:-main}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/myorg-extensions-app
      - ./provisioning:/etc/grafana/provisioning
